name: tidepool-analytics
dependencies:
- python=3
- cython
- pandas
- requests
- pylint
- spyder
- openpyxl
- xlrd
- xlsxwriter
- matplotlib
- scikit-learn
- plotly
- r
- r-essentials
- pip:
  - python-dotenv
  - -e git+https://github.com/tidepool-org/data-analytics@etn/aws-linux-compatibility#egg=tidals\&subdirectory=tidals
